name: Gerar Cliente ID

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🚀 Rodar script de geração de Cliente_ID
        run: node --experimental-modules scripts/gerarClienteId.js
        env:
          GOOGLE_CLIENT_EMAIL: client-kanban-system@client-kanban-system.iam.gserviceaccount.com
          GOOGLE_PRIVATE_KEY: |
            -----BEGIN PRIVATE KEY-----
            MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDhZi9pCKEZ4jhH
            4aujgW95y5052CQrhSl1W81xIRmcNTdL2Z6iCaZBDjutp7JYbsGP+dSMmSfbFjVi
            zwFi5AHsY2e4CmTqXZ6kmKPpSPV98NkL5Kefj6Gml1CQuRA1LuDCWCA6JZriJbis
            MfuClPVNv/YMJgCv3Fc6AOPbA7YmnX+l1uahXqQ6WojsvaHcy5oDKMdgl1PRcgmY
            hr9rqBI7WLGi/crVve5UySjlYDrZ3pbcrN4p6Lw2/6GkIKLgVThebOEVdrqjDC/W
            inuAj/19UaXeJw+i9ZTNEADZL9PkdDceVad64elZZ4MiMP9exa3sd27p4Py4HOQp
            CjUvkffRAgMBAAECggEAF5DbfBvO3CnuwHUzwNCTmyRSt+2FOpedkgubGyzexJo7
            wc5q634ex8Z5LtrNprlNu4PfWSPaKunTgxUpi/FS0ihCe9d6XZaUM5lR6d4a7KP1
            zWyGqgQWXpiLb9Ypf6X7Edas5+dunh5bhIVlSm3Qh+R+ER8YC0r6Q7I8IHXu4XJ7
            xiQfOJzG54RLNxv0hYjffzFvU/OBbdYfg8lgd8SWprWCtwBzLEw+itBHfWgTw8g8
            uyOQAQA49DI97WmSLpxaG2XZD1miJjKvyR2AXpSQx8oWgAfnCY/CVMFqr0shxA4N
            VlajjMChhzFgJZOaQoLPapuC3NY8jGu+zl05nI/FwQKBgQD/rzQ2F2E1k6NDE8HR
            GR5rwAJfLuZqpFr3WRMk3lKhlObuF2TypmdsFXANA116f8vARKVhhP7n+X/Ik7z/
            Nr2DhUMLUlnt7UB101LY9k6M4RqGVOYrUKxsKuD+4YnLooiCBqJyXUlo1U11V/N7
            3mKciqwq8Kd8JhCB8jhpQnpFPQKBgQDhrWlAbXIqysMgW+3ICnYlcUs50HIXmoA6
            +aCTyMYIEItqTqeO7cDOzHf1Q1DeGMQPtI/2a9EY+C/QtT8KUx5UdyEAKO8Dadin
            fR3f9YXCpHojffSPYbk/Ljkw3eBGwY3NvIoKGRsIOBM0PJNNLIIUnek/xqvGted/
            3/2VwpkuJQKBgQCTf9A/8CbdEImblZc2+CWrhT4ZCOZV2PC9Rn6bw0GqA0thSM+s
            h8CcApX8e9d+ZqD1DuTVKDMhQbas0EW0eTDE4ai2rFBCyJ5qGnntvdG8xdNWcT3C
            +SwuzmGzyAqFFgNn90nZbeV+e6bOrelBqR38Lqd5shD8trzJKiHO31HIBQKBgQDI
            Eyt62Q0cbwKrD5UxgkTYUSb2LJzZ3DnPDzyTiK44vCI9r1nR12rWbGP1ZyasoJxB
            qDzxpQiN8IrDp8wp5SLAk5UIRUIRbqeLZds0kMFznMpD6QkGjQbkwqAleK+7SyHi
            wkJHTZavpLcx2nplMw5oJM+DoSjtVJvWvMhfG1UemQKBgBOzUUfp4IJaWELa9Nig
            e1d24gt0nNZaV5zKDz47QUNw0G6MPxxgt8ndOJMs3LE7BglT9L+QlJ8HbuUSHlPC
            KLpFIrhMgO6KGqVtetrvhCCrhdLA8NYRslpoTdVjPZYSvk3vVch84L0iq0dPao8i
            A4KTQXgVskUXdmx0rgvqn2yi
            -----END PRIVATE KEY-----
          SPREADSHEET_ID: 1GdsU2GU08Nuhiqb28iYcdmElZqKYmkQof5PRRBXdI64

