name: NPM Install

on:
  workflow_dispatch:

jobs:
  install-deps:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Instalar dependências
        run: npm install

      - name: ✅ Commit do package-lock.json atualizado
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add package-lock.json
          git commit -m "chore: atualizar dependências via Actions" || echo "Sem alterações"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
